### ISSUE TITLE
LDAP3 version

### ISSUE THREAD

**Issue by naominitel** [marcoh00/radicale-auth-ldap#6]
Is there any specific reason why versions of LDAP3 >= 2.4 are not supported or is this just because they are untested?

I'd assume that newer 2.X versions would stay backwards-compatible. Supporting them would allow me to more easily package this module for my distribution.

**Comment by marcoh00** [comment]
Hi,

sorry for answering so late. ldap3 had quite a record for me for deprecating and removing things (in the end, this is why this repo exists in the first place, to keep Raoul's code running :wink: ), so I decided to pin ldap3's version to a known-good-setting. Feel free to test it works with newer versions, I will happily update setup.py then :-)

**Comment by marcoh00** [comment]
Fixed by #10
